<a href="https://colab.research.google.com/github/Jyothsna-ks/Inomatics_Data-Science-Internship/blob/main/NLP_Task2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from google.colab import files
uploaded = files.upload()

Saving IMDB Dataset.csv.zip to IMDB Dataset.csv.zip

In [ ]:
import numpy as np
import pandas as pd
import re
import string

# NLP
import nltk
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer

# Sklearn
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer
from sklearn.metrics import accuracy_score, classification_report

from sklearn.linear_model import LogisticRegression
from sklearn.naive_bayes import MultinomialNB
from sklearn.tree import DecisionTreeClassifier

In [ ]:
import nltk
nltk.download('stopwords')
nltk.download('wordnet')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.
[nltk_data] Downloading package wordnet to /root/nltk_data...

True

In [ ]:
import pandas as pd
df = pd.read_csv("IMDB Dataset.csv.zip")
df.head()

                                              review sentiment
0  One of the other reviewers has mentioned that ...  positive
1  A wonderful little production. <br /><br />The...  positive
2  I thought this was a wonderful way to spend ti...  positive
3  Basically there's a family where a little boy ...  negative
4  Petter Mattei's "Love in the Time of Money" is...  positive

In [ ]:
print("Shape:", df.shape)
print("\nClass Distribution:")
print(df['sentiment'].value_counts())

Shape: (50000, 2)

Class Distribution:
sentiment
positive    25000
negative    25000
Name: count, dtype: int64

In [ ]:
df['sentiment'].isna().sum()

np.int64(50000)

In [ ]:
df[df['sentiment'].isna()].head()

                                              review  ...                                         clean_text
0  One of the other reviewers has mentioned that ...  ...  one reviewer mentioned watching oz episode you...
1  A wonderful little production. <br /><br />The...  ...  wonderful little production br br filming tech...
2  I thought this was a wonderful way to spend ti...  ...  thought wonderful way spend time hot summer we...
3  Basically there's a family where a little boy ...  ...  basically there family little boy jake think t...
4  Petter Mattei's "Love in the Time of Money" is...  ...  petter matteis love time money visually stunni...

[5 rows x 3 columns]

In [66]:
nltk.download('stopwords')
nltk.download('punkt')

from nltk.corpus import stopwords
from nltk.stem import PorterStemmer
from nltk.tokenize import word_tokenize

stop_words = set(stopwords.words('english'))
stemmer = PorterStemmer()

def preprocess(text):
    text = str(text).lower()  # Lowercasing

    text = re.sub(r"http\S+|www\S+", '', text)  # Remove URLs
    text = re.sub(r"[^a-zA-Z]", " ", text)      # Remove punctuation/special chars

    tokens = word_tokenize(text)               # Tokenization

    tokens = [stemmer.stem(word) for word in tokens if word not in stop_words]  # Stopwords + Stemming

    return " ".join(tokens)

# Apply preprocessing
df['cleaned_review'] = df['review'].apply(preprocess)

df[['review', 'cleaned_review']].head()

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.

Empty DataFrame
Columns: [review, cleaned_review]
Index: []

In [ ]:
import re
import string
df['clean_text'] = df['review'].apply(preprocess_text)
X = df['clean_text']
y = df['sentiment']
df['sentiment'] = df['sentiment'].astype(str)
df['sentiment'] = df['sentiment'].str.strip().str.lower()
df['sentiment'] = df['sentiment'].map({'positive':1, 'negative':0})
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

In [ ]:
X_train

39087    thats kept asking many fight screaming match s...
30893    watch entire movie could watch entire movie st...
45278    touching love story reminiscent in mood love ...
16398    latterday fulci schlocker totally abysmal conc...
13653    first firmly believe norwegian movie continual...
                               ...
11284    shadow magic recapture joy amazement first mov...
44732    found movie quite enjoyable fairly entertainin...
38158    avoid one terrible movie exciting pointless mu...
860      production quite surprise absolutely love obsc...
15795    decent movie although little bit short time pa...
Name: clean_text, Length: 40000, dtype: object

In [ ]:
X_test

33553    really liked summerslam due look arena curtain...
9427     many television show appeal quite many differe...
199      film quickly get major chase scene ever increa...
12447    jane austen would definitely approve onebr br ...
39489    expectation somewhat high went see movie thoug...
                               ...
28567    although casper van dien michael rooker genera...
25079    liked movie wasnt really sure started watching...
18707    yes nonsingaporeans cant see whats big deal fi...
15200    far film go likable enough entertaining charac...
5857     saw anatomy year ago dubbed friend house dont ...
Name: clean_text, Length: 10000, dtype: object

In [ ]:
y_train

39087   NaN
30893   NaN
45278   NaN
16398   NaN
13653   NaN
         ..
11284   NaN
44732   NaN
38158   NaN
860     NaN
15795   NaN
Name: sentiment, Length: 40000, dtype: float64

In [ ]:
y_test

33553   NaN
9427    NaN
199     NaN
12447   NaN
39489   NaN
         ..
28567   NaN
25079   NaN
18707   NaN
15200   NaN
5857    NaN
Name: sentiment, Length: 10000, dtype: float64

In [70]:
df = df.dropna(subset=['sentiment'])

In [73]:
df['sentiment'] = df['sentiment'].astype(str)
df['sentiment'] = df['sentiment'].str.strip().str.lower()
df['sentiment'] = df['sentiment'].map({'positive':1, 'negative':0})

In [74]:
print(df['sentiment'].dtype)   # should be int or float
print(df['sentiment'].isna().sum())  # should be 0

int64
0

In [81]:
from sklearn.linear_model import LogisticRegression
from sklearn.naive_bayes import MultinomialNB
from sklearn.tree import DecisionTreeClassifier

#Logistic Regression
lr = LogisticRegression(max_iter=1000)
# Naive Bayes
nb = MultinomialNB()
# Decision Tree
dt = DecisionTreeClassifier(max_depth=10, random_state=42)

In [77]:
from sklearn.metrics import accuracy_score, classification_report

def evaluate_model(y_test, y_pred, model_name):
    print(f"\n{model_name}")
    print("Accuracy:", accuracy_score(y_test, y_pred))
    print(classification_report(y_test, y_pred))

evaluate_model(y_test, y_pred_lr, "Logistic Regression")
evaluate_model(y_test, y_pred_nb, "Naive Bayes")
evaluate_model(y_test, y_pred_dt, "Decision Tree")

NameError: name 'y_pred_lr' is not defined